### ISSUE TITLE
Using ngBlur causes $apply already in progress error

### ISSUE THREAD

**Issue by adamk33n3r** [angular-ui/ui-date#135]
Using ngBlur causes $apply already in progress error. ngChange works fine but I'd like to have an event when the input is blurred.

**Comment by alexanderchan** [comment]
ngBlur is more a part of angular than this component.  One workaround is to evalAsync so that your code runs after the apply finishes.  

https://github.com/angular/angular.js/blob/master/src/ng/directive/ngModel.js#L1078-L1086

          element.on('blur', function(ev) {
            if (modelCtrl.$touched) return;

            if ($rootScope.$$phase) {
              scope.$evalAsync(modelCtrl.$setTouched);
            } else {
              scope.$apply(modelCtrl.$setTouched);
            }
          });

$$phase is more of a private thing that probably shouldn't be used outside of angular, but your function could just always evalAsync in order to ensure that the function is called at the end of the apply in progress.

**Comment by alexanderchan** [comment]
There is also an [answer from a contributor to angular](http://stackoverflow.com/questions/22698058/apply-already-in-progress-error-when-using-typeahead-plugin-found-to-be-relate
), it is a bit older but probably could help here.  I've seen this sometimes called a "safe" apply.  Hope that helps.

**Comment by alexanderchan** [comment]
One month, closing
