### ISSUE TITLE
date pick on ie8  -> link to website index 

### ISSUE THREAD

**Issue by outruner** [angular-ui/ui-date#71]
Hello all, I have the folowing issue on ie8. My form url is: www.mysite.com/reservation#head. When a date is picked, link is www.mysite.com/#. On FF and chrome there is no issue, but on ie8 the page will reload and go to the index. Thanks for helping

**Comment by jusefb** [comment]
This is probably to late know but I think I just had the same problem today. Three hours later :) I think I have found the cause. I was building a directive and using the ui-date plugin there. The issue above occurred when I used "data-ng-model" attribute instead of "ng-model" inside the directive. Switching to "ng-model" solved the problem. Could there be a potential issue where the plugin specificly looks for "ng-model" and does not allow data- prefixed attributes for the directive?

Cheers

Jusef

**Comment by alexanderchan** [comment]
@jusefb thanks for the feedback on this.  Strange that ie8 is not supporting the data-* prefix properly, which version of angular are you using, it seems that data- is supposed to be supported since [1.0.3](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#103-bouncy-thunder-2012-11-26) but as angular no longer supports ie8 it will probably be hard to get any fixes on this.

I think the ngModel is at least being used as defined in the [docs](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController) and I don't know of an elegant way to also support data prefixes as I can see it already works with data-prefixes on modern browsers.
